package pandemic.game;

public enum PhaseStep {
    START_PHASE,
    END_PHASE,

    SETUP_CHOOSE_PLAYER_ROLES,
    SETUP_CHOOSE_FUNDED_EVENTS,
    SETUP_BUILD_PLAYER_DECK,
    SETUP_PLACE_INITIAL_DISEASES,

    PLAY_TAKE_ACTIONS,
    PLAY_DRAW_PLAYER_CARDS,
    PLAY_DISCARD_TO_HAND_LIMIT,
    PLAY_INFECT_CITIES
}
